kafka:
  # Event Messages
  events:
    # topic_maps (acapy topic regex to kafka topic template): A mapping from regex
    #     matching ACA-Py event topics to kafka topics. The Kafka topic can be templated;
    #     the plugin will insert the following values:
    #
    #     $wallet_id: the id of the sub-wallet emitting the event or "base" if
    #         the base wallet
    #     $state: the state associated with the event (not all events have state)
    #     $topic: the acapy event topic
    #     $category: the acapy topic "category" or the portion following
    #         "acapy::record::" and "acapy::webhook::" in acapy events.
    topic_maps:
      "^acapy::webhook::(.*)$": "webhook-$wallet_id"
      "^acapy::record::connections::.*": "connections-$wallet_id"
      "^acapy::record::issue_credential::.*": "issue-credential-v1-$wallet_id"
      "^acapy::record::issue_credential_v2_0::.*": "issue-credential-v2-$wallet_id"
      "^acapy::record::present_proof::.*": "present-proof-v1-$wallet_id"
      "^acapy::record::present_proof_v2_0::.*": "present-proof-v2-$wallet_id"
      # TODO There are likely more topics you are interested in

    producer:
      bootstrap_servers: kafka

      # Additional parameters can be added here to be picked up automatically by the component
      # To see the full list please consult the following documentation under the section `Parameters`:
      # https://aiokafka.readthedocs.io/en/stable/api.html#producer-class

  # Inbound Messages
  inbound:
    topics:
      - acapy-inbound-message
    consumer:
      group_id: inbound

      # Additional parameters can be added here to be picked up automatically by the component
      # To see the full list please consult the following documentation under the section `Parameters`:
      # https://aiokafka.readthedocs.io/en/stable/api.html#consumer-class

  # Outbound Messages
  outbound:
    topic: acapy-outbound-message
    producer:
      bootstrap_servers: kafka

      # Additional parameters can be added here to be picked up automatically by the component
      # To see the full list please consult the following documentation under the section `Parameters`:
      # https://aiokafka.readthedocs.io/en/stable/api.html#producer-class
