[tool.poetry]
name = "kafka-events"
version = "0.1.0"
description = "ACA-Py Event to Kafka Bridge"
authors = ["Daniel Bluhm <dbluhm@pm.me>"]

[tool.poetry.dependencies]
python = "^3.6.9"
aries-cloudagent = {git = "https://github.com/hyperledger/aries-cloudagent-python", rev = "main"}

[tool.poetry.dev-dependencies]
black = "^21.4b2"
flake8 = "^3.9.1"
pre-commit = "^2.12.1"
pytest = "^6.2.3"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
