version: '3'
services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 22181:2181

  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 29092:9092
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # restproxy:
  #   image: confluentinc/cp-kafka-rest
  #   restart: always
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   hostname: restproxy
  #   container_name: restproxy
  #   environment:
  #     KAFKA_REST_HOST_NAME: restproxy
  #     KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
  #     KAFKA_REST_LISTENERS: http://0.0.0.0:8086

  # kafka-visuals:
  #   image: kbhargava/kafka-visuals
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #   command: zookeeper:2181 kafka:9092 DEV

  #*************************************************************
  # agency: Edison Agency.
  #*************************************************************
  agency:
    image: acapy-kafka-queue
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 3001:3001
    # depends_on:
      # - kafka
      # - zookeeper
      # - restproxy
    volumes:
      - ./configs:/home/indy/configs:z
    environment:
      - WAIT_BEFORE_HOSTS=5
      # - WAIT_HOSTS=zookeeper:2181,kafka:9092,restproxy:8086
      - WAIT_HOSTS_TIMEOUT=120
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=60
    command: start --arg-file ./configs/agency.yml --endpoint http://agency:3000


  #*************************************************************
  # mediator: Edison Mediator.
  #*************************************************************
  mediator-tunnel:
    image: reflectivedevelopment/agent-tunnel
    command: mediator:3000 -p 4040 --host ${AGENT_TUNNEL_HOST}

  mediator:
    image: acapy-kafka-queue
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 3002:3001
    # depends_on:
      # - kafka
      # - zookeeper
      # - restproxy
    volumes:
      - ./configs:/home/indy/configs:z
      - ./agent-tunnel-wait.sh:/home/indy/agent-tunnel-wait.sh:z
    environment:
      - WAIT_BEFORE_HOSTS=5
      # - WAIT_HOSTS=zookeeper:2181,kafka:9092,restproxy:8086
      - WAIT_HOSTS_TIMEOUT=120
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=60
      - TUNNEL_HOST=mediator-tunnel
      - TUNNEL_PORT=4040
    entrypoint: /bin/sh -c '/wait && ./agent-tunnel-wait.sh poetry run aca-py "$$@"' --
    command: start --arg-file ./configs/mediator.yml


  #*************************************************************
  # setup: Setup connections between agency and mediator. In a *
  # "Juggernaut" fashion!                                      *
  #*************************************************************

  setup:
      container_name: juggernaut
      build:
        context: ./setup
        dockerfile: Dockerfile
      environment:
        - WAIT_BEFORE_HOSTS=6
        - WAIT_HOSTS=agency:3001,mediator:3001
        - WAIT_HOSTS_TIMEOUT=120
        - WAIT_SLEEP_INTERVAL=1
        - WAIT_HOST_CONNECT_TIMEOUT=60
        - AGENT_ADMIN_URL=http://agency:3001
        - MEDIATOR_ADMIN_URL=http://mediator:3001
      depends_on:
        - agency
        - mediator
