kafka-queue:
  # Events
  events:
    producer:
      bootstrap_servers: kafka
    topic_maps:
      "^acapy::webhook::(.*)$": "webhook-$wallet_id"
      "^acapy::record::connections::.*": "connections-$wallet_id"
      "^acapy::record::issue_credential::.*": "issue-credential-v1-$wallet_id"
      "^acapy::record::issue_credential_v2_0::.*": "issue-credential-v2-$wallet_id"
      "^acapy::record::present_proof::.*": "present-proof-v1-$wallet_id"
      "^acapy::record::present_proof_v2_0::.*": "present-proof-v2-$wallet_id"
      # TODO There are likely more topics we are interested in

  # Inbound Messages
  inbound:
    topics:
      - "acapy-inbound-message"
    consumer:
      group_id: "aca-py agent"


  # Outbound Messages
  outbound:
    producer:
      bootstrap_servers: kafka
    topic: "acapy-outbound-message"
